name: Android CI

on:
  push:
    paths-ignore:
      - '**.md'
      - 'fastlane/**'
      - '.github/**'
      - '!.github/workflows/android.yml'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'fastlane/**'
      - '.github/**'
      - '!.github/workflows/android.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assembleRelease
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: app/build/outputs/apk/
          retention-days: 7
